# This is a basic workflow to help you get started with Actions

name: Vividly-Demo
on:    # triggers
  push:
    branches: [ "main" ]     # branch filter
  pull_request:
    branches: [ "main" ]     # branch filter
  workflow_dispatch:     # run workflow manually from Actions tab
jobs:     # jobs that can run sequentially or in parallel
  build:
    runs-on: ubuntu-latest    # job runner type(s)
    steps:    # steps are a sequence of tasks executed as part of the job
      - uses: actions/checkout@v3    # checkout repo under $GITHUB_WORKSPACE
      - name: Run a one-line script    # runs a single liner shell command
        run: echo Hello, world!
      - name: Run a multi-line script    #  runs a multi liner shell command
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
